### ISSUE TITLE
Possible OME Error in SUCCESSIVE_SP function code?

### ISSUE THREAD

**Issue by VikashKothary** [markormesher/cs-notes#4]
The function SUCCESSIVE_SP on page 31 may have an error. On line 25, your code uses '+' to combine the existing and new flow, however on the Slides it is using xor '⊕'. Not sure if the '+' is also acceptable but I thought I'd point it out.

**Comment by markormesher** [comment]
Hi Vikash. The symbol used in the slides (`⊕`) usually does mean logical XOR in most contexts, but in the context of flows it just means "combining flows" (as described at the bottom of page 22 and the top of page 23). The code in these notes should use `⊕` rather than `+`, but the symbol doesn't display nicely in the LaTeX code format! I'll add a comment to the notes this evening (although it'll probably only help future years now).

Thanks for pointing it out 😃
